config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'
  resources :restaurants, only: [:index, :show, :destroy] do
    resources :reviews, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, length: { minimum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
    @reviews = @restaurant.reviews.order(created_at: :desc)
  end

  def destroy
    @restaurant.destroy
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: :create

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      respond_to do |format|
        format.html { redirect_to @restaurant }
        format.js # will run create.js.erb
      end
    else
      respond_to do |format|
        @reviews = @restaurant.reviews
        format.html { render 'restaurants/show' }
        format.js # same as above
      end
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <div style="max-width: 600px; margin: 0 auto;">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/restaurants/_restaurant.html.erb
<li data-restaurant-id="<%= restaurant.id %>">
  <%= link_to restaurant.name, restaurant_path(restaurant) %>
  <%= link_to "Delete", restaurant_path(restaurant), method: :delete, remote: true %>
</li>

app/views/restaurants/destroy.js.erb
console.log('hello from destroy.js.erb')
document.querySelector("[data-restaurant-id='<%= @restaurant.id %>']")
  .remove();

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
  <%= render @restaurants %>
</ul>

app/views/restaurants/show.html.erb
<h1 style="display: inline-block"><%= @restaurant.name %></h1>
<%= link_to "Back", :back %>
<%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=15&size=400x300&sensor=false&maptype=roadmap&markers=color:red|#{@restaurant.address}" %>

<h2><%= pluralize @restaurant.reviews.size, "review" %></h2>

<%= render 'reviews/form', restaurant: @restaurant, review: @review  %>

 <div id="reviews">
   <ul>
     <%= render @reviews %>
   </ul>
 </div>

app/views/reviews/_form.html.erb
<%= simple_form_for [restaurant, review], remote: true do |form| %>
  <%= form.input :content, as: :text %>
  <%= form.button :submit %>
<% end %>


<script>
  console.log("I am the form")
</script>

app/views/reviews/_review.html.erb
<p><%= review.content %></p>

app/views/reviews/create.js.erb
console.log("Hello from create.js.erb")

function renderReview(reviewHTML) {
  const reviews = document.getElementById('reviews');
  reviews.insertAdjacentHTML('afterbegin', reviewHTML);
}

function refreshForm(formHTML) {
  const reviewForm = document.getElementById('new_review');
  reviewForm.innerHTML = formHTML;
}

<% if @review.errors.any? %>
  refreshForm('<%= j render "reviews/form", restaurant: @restaurant, review: @review %>')
<% else %>
  renderReview('<%= j render @review %>')
  refreshForm('<%= j render "reviews/form", restaurant: @restaurant, review: Review.new %>')
<% end %>